# Linear algebra and numpy

In [1]:
import numpy as np
import numpy.linalg as la # the linear algebra module

# Vector - vector operations

- Cross product: $\vec{z} = \vec{x} \times \vec{y}$

- Dot product: $\displaystyle \vec{x} \cdot \vec{y} = \sum_i x_i y_i$

In [2]:
x = np.array([1, 0, 0])
y = np.array([0, 1, 0])

z = np.cross(x, y)
print('the cross product is:', z)

d = np.dot(x, y)
print('the dot product is:', d)

the cross product is: [0 0 1]
the dot product is: 0


Recall that `*` refers to elementwise multiplication:

In [3]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

p = x * y
print('this is a element-wise multiplication: ', p)

this is a element-wise multiplication:  [ 4 10 18]


For complex numbers (quantum mechanics) the bra requires a complex conjugation.

This is done with `np.vdot`

- `np.vdot(x,y) =` $\displaystyle \langle x | y \rangle = \sum_i x_i^* y_i$

In [4]:
x = np.array([1j, 0, 0])
y = np.array([1, 2, 3])

p = np.vdot(x, y)
print('vdot takes the conjugate of the left operator: ', p)

vdot takes the conjugate of the left operator:  -1j


In [5]:
x = np.array([1, 1, 0])
print('The norm of a vector is:', la.norm(x))

The norm of a vector is: 1.4142135623730951


## Matrix - matrix operations

In [20]:
# let's use simple 2x2 matrices
A = np.array([[0, 1], [1, 0]])
B = np.array([[1, 2], [3, 4]])

print('the matrix product is: \n', np.dot(A, B))

print('which can be written as: \n', A @ B)

print('this is an element-wise multiplication: \n', A * B)

the matrix product is: 
 [[3 4]
 [1 2]]
which can be written as: 
 [[3 4]
 [1 2]]
this is an element-wise multiplication: 
 [[0 2]
 [3 0]]


To calculate powers of a matrix, use `np.linalg.matrix_power(A, n)`

In [21]:
print('This is an elementwise power: \n', A**2)

print('This is the matrix squared: \n', la.matrix_power(A, 2))

print('Or simply:\n', A @ A)

This is an elementwise power: 
 [[0 1]
 [1 0]]
This is the matrix squared: 
 [[1 0]
 [0 1]]
Or simply:
 [[1 0]
 [0 1]]


In [22]:
print('The determinant:', la.det(A))
print('The inverse:', la.inv(A))
print('The trace:', np.trace(A))
# notice np instead of la... confusing...

The determinant: -1.0
The inverse: [[0. 1.]
 [1. 0.]]
The trace: 0


## Matrix - vector operations

As a simple example, consider the system of equations

$$3x_0 + x_1 = 9$$

$$2x_1 + x_0 = 8$$

or simply:

$$\begin{pmatrix}3 & 1 \\ 1 & 2\end{pmatrix}\begin{pmatrix}x_0 \\ x_1\end{pmatrix} = \begin{pmatrix}9 \\ 8\end{pmatrix}$$

In [23]:
A = np.array([[3, 1], [1, 2]])
B = np.array([9, 8])

# solve using the linear system solver
X = la.solve(A, B)
print('the solution is:', X)

# is the same as applying the inverse
# but we don't like inverses...
X = np.linalg.inv(A) @ B
print('the solution is:', X)

the solution is: [2. 3.]
the solution is: [2. 3.]


A quantum mechanics matrix element can be written as

In [24]:
A = np.array([[0, -1j], [1j, 0]])

x = np.array([1, 1j])/np.sqrt(2)
y = np.array([1, -1j])/np.sqrt(2)

print('<x|A|y> =', np.vdot(x, np.dot(A, y)))
print('<x|A|x> =', np.vdot(x, A.dot(x)))
print('<y|A|y> =', np.vdot(y, A @ y))

<x|A|y> = 0j
<x|A|x> = (0.9999999999999998+0j)
<y|A|y> = (-0.9999999999999998+0j)


# Eigenproblems

For hermitian matrices, use `la.eigh(...)` or `la.eigvalsh(...)`

For general matrices, use `la.eig(...)` or `la.eigvals(...)`

In [25]:
A = np.array([[0, 1], [1, 0]])
print(A)

[[0 1]
 [1 0]]


In [26]:
# eigenvalues only: if A is hermitian, 
#                   sorted from lowest to highest
evals = la.eigvalsh(A)
print(evals)

[-1.  1.]


In [27]:
# eigenvalues and eigenvectors
evals, evects = la.eigh(A)
print(evals)

[-1.  1.]


In [28]:
# the eigenvectors are stored in columns
print('eval =', evals[0], # all lines, column 0
      ' and its eigenvector =', evects[:,0]) 

print('eval =', evals[1], # all lines, column 1
      ' and its eigenvector =', evects[:,1]) 

eval = -1.0  and its eigenvector = [-0.70710678  0.70710678]
eval = 1.0  and its eigenvector = [0.70710678 0.70710678]
